import json
from pathlib import Path

from app.eval_dataset import load_evaluation_dataset


ROOT = Path(__file__).resolve().parents[1]
TEST_PATH = ROOT / "eval" / "test_questions.json"
DOCUMENT = "motor_manual.pdf"


# ID, question, category, type, pages, chunks, reference answer
ANSWERABLE = [
    (
        "Q050",
        "What are the three main categories of in-plant "
        "electrical distribution and power-quality problems "
        "identified by the sourcebook?",
        "power_quality",
        "factual",
        [51],
        ["p51_c0"],
        "The three categories are voltage problems, including "
        "outages, sags, transients, surges, harmonics and other "
        "signal distortions; poor power factor; and "
        "electromagnetic interference.",
    ),
    (
        "Q051",
        "What five factors does the sourcebook identify "
        "as possible causes of voltage deviations?",
        "power_quality",
        "factual",
        [52],
        ["p52_c0"],
        "The five factors are changes in loads associated "
        "with daily or seasonal operation, improperly sized "
        "transformers, undersized conductors, poor connections, "
        "and sources of low power factor in the distribution system.",
    ),
    (
        "Q052",
        "How do static and dynamic UPS systems differ "
        "in the way they provide backup power?",
        "backup_power",
        "comparison",
        [55],
        ["p55_c1"],
        "Static UPS systems use batteries to supply power "
        "during voltage sags or interruptions. Dynamic UPS "
        "systems use the inertia of a rotating mass, usually "
        "a flywheel, to drive a generator long enough "
        "for an engine to start and take over.",
    ),
    (
        "Q053",
        "Which energy and environmental metrics can "
        "help demonstrate that an industrial efficiency "
        "project supports corporate energy-management goals?",
        "energy_economics",
        "factual",
        [57],
        ["p57_c1"],
        "Suggested metrics include expected annual energy "
        "savings in kWh or MMBtu, the percentage reduction "
        "in factory energy use, and greenhouse gas "
        "emission reductions in tonnes per year.",
    ),
    (
        "Q054",
        "According to the sourcebook, how can a company "
        "estimate the additional shareholder value created "
        "by an energy-efficiency project?",
        "energy_economics",
        "numerical",
        [59],
        ["p59_c0", "p59_c1"],
        "First estimate the annual savings or addition "
        "to earnings generated by the project. Multiplying "
        "that earnings increase by the company's "
        "price-to-earnings ratio gives the estimated "
        "additional shareholder value.",
    ),
    (
        "Q055",
        "What two simultaneous measurements does a "
        "wattmeter require, and how can electricity costs "
        "be estimated for a motor operating at constant load?",
        "motor_measurement",
        "multi_part",
        [61],
        ["p61_c0"],
        "A wattmeter requires simultaneous voltage and "
        "current measurements. For a motor operating "
        "at constant load, multiply measured power in kW "
        "by operating hours and the electricity rate "
        "to estimate electricity costs.",
    ),
    (
        "Q056",
        "What is the purpose of the NOx and Energy Assessment "
        "Tool, and which industries is it intended to help?",
        "assessment_tools",
        "factual",
        [64],
        ["p64_c0"],
        "The NOx and Energy Assessment Tool helps petroleum "
        "refining and chemical plants assess nitrogen oxide "
        "emissions and analyze how energy-efficiency "
        "improvements could reduce them. It supports "
        "what-if analyses for equipment including fired "
        "heaters, boilers, gas turbines and reciprocating engines.",
    ),
    (
        "Q057",
        "How does the Energy Performance Indicator Tool "
        "measure industrial energy-performance improvements?",
        "energy_management",
        "factual",
        [66],
        ["p66_c0"],
        "The Energy Performance Indicator Tool uses "
        "regression analysis to calculate energy-performance "
        "indicators, normalizing for weather, production "
        "and other relevant variables.",
    ),
]


UNANSWERABLE = [
    (
        "Q058",
        "At exactly what time did the most recent "
        "voltage sag occur at my factory?",
    ),
    (
        "Q059",
        "How much did my facility pay for its "
        "most recent motor-rewinding invoice?",
    ),
    (
        "Q060",
        "Who is the electrical contractor scheduled "
        "to inspect my factory next Tuesday?",
    ),
]


def main():
    existing = load_evaluation_dataset(TEST_PATH)

    expected_ids = {
        f"Q{number:03d}"
        for number in range(43, 50)
    }

    actual_ids = {
        item["question_id"]
        for item in existing
    }

    if len(existing) != 7 or actual_ids != expected_ids:
        raise SystemExit(
            "Expected exactly Q043-Q049 in the existing "
            "test dataset. No changes made."
        )

    new_questions = []

    for (
        question_id,
        question,
        category,
        question_type,
        pages,
        chunks,
        reference_answer,
    ) in ANSWERABLE:
        new_questions.append({
            "question_id": question_id,
            "question": question,
            "category": category,
            "question_type": question_type,
            "answerable": True,
            "expected_document": DOCUMENT,
            "expected_pages": pages,
            "relevant_chunk_ids": [
                f"{DOCUMENT}_{chunk}"
                for chunk in chunks
            ],
            "reference_answer": reference_answer,
        })

    for question_id, question in UNANSWERABLE:
        new_questions.append({
            "question_id": question_id,
            "question": question,
            "category": "out_of_scope",
            "question_type": "unanswerable",
            "answerable": False,
            "expected_document": None,
            "expected_pages": [],
            "relevant_chunk_ids": [],
            "reference_answer": None,
        })

    updated = existing + new_questions

    ids = [item["question_id"] for item in updated]

    if len(ids) != len(set(ids)):
        raise SystemExit(
            "Duplicate question IDs detected. "
            "No changes made."
        )

    temp_path = TEST_PATH.with_name(
        "test_questions.batch2.tmp.json"
    )

    temp_path.write_text(
        json.dumps(
            updated,
            indent=2,
            ensure_ascii=False,
        ) + "\n",
        encoding="utf-8",
    )

    # Validate before replacing the original file.
    load_evaluation_dataset(temp_path)

    temp_path.replace(TEST_PATH)

    print(f"Added questions: {len(new_questions)}")
    print(f"Total test questions: {len(updated)}")
    print(
        "Answerable:",
        sum(item["answerable"] for item in updated),
    )
    print(
        "Unanswerable:",
        sum(not item["answerable"] for item in updated),
    )


if __name__ == "__main__":
    main()